# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.7.0-04
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import nexuscli
from nexuscli.rest import ApiException
from nexuscli.apis.tasks_api import TasksApi


class TestTasksApi(unittest.TestCase):
    """ TasksApi unit test stubs """

    def setUp(self):
        self.api = nexuscli.apis.tasks_api.TasksApi()

    def tearDown(self):
        pass

    def test_get_task_by_id(self):
        """
        Test case for get_task_by_id

        Get a single task by id
        """
        pass

    def test_get_tasks(self):
        """
        Test case for get_tasks

        List tasks
        """
        pass

    def test_run(self):
        """
        Test case for run

        Run task
        """
        pass

    def test_stop(self):
        """
        Test case for stop

        Stop task
        """
        pass


if __name__ == '__main__':
    unittest.main()
