# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.7.0-04
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import nexuscli
from nexuscli.rest import ApiException
from nexuscli.apis.search_api import SearchApi


class TestSearchApi(unittest.TestCase):
    """ SearchApi unit test stubs """

    def setUp(self):
        self.api = nexuscli.apis.search_api.SearchApi()

    def tearDown(self):
        pass

    def test_search(self):
        """
        Test case for search

        Search components
        """
        pass

    def test_search_and_download_assets(self):
        """
        Test case for search_and_download_assets

        Search and download asset
        """
        pass

    def test_search_assets(self):
        """
        Test case for search_assets

        Search assets
        """
        pass


if __name__ == '__main__':
    unittest.main()
