# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.7.0-04
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import nexuscli
from nexuscli.rest import ApiException
from nexuscli.apis.script_api import ScriptApi


class TestScriptApi(unittest.TestCase):
    """ ScriptApi unit test stubs """

    def setUp(self):
        self.api = nexuscli.apis.script_api.ScriptApi()

    def tearDown(self):
        pass

    def test_add(self):
        """
        Test case for add

        Add a new script
        """
        pass

    def test_browse(self):
        """
        Test case for browse

        List all stored scripts
        """
        pass

    def test_delete(self):
        """
        Test case for delete

        Delete stored script by name
        """
        pass

    def test_edit(self):
        """
        Test case for edit

        Update stored script by name
        """
        pass

    def test_read(self):
        """
        Test case for read

        Read stored script by name
        """
        pass

    def test_run1(self):
        """
        Test case for run1

        Run stored script by name
        """
        pass


if __name__ == '__main__':
    unittest.main()
