# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.7.0-04
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import nexuscli
from nexuscli.rest import ApiException
from nexuscli.apis.components_api import ComponentsApi


class TestComponentsApi(unittest.TestCase):
    """ ComponentsApi unit test stubs """

    def setUp(self):
        self.api = nexuscli.apis.components_api.ComponentsApi()

    def tearDown(self):
        pass

    def test_delete_component(self):
        """
        Test case for delete_component

        Delete a single component
        """
        pass

    def test_get_component_by_id(self):
        """
        Test case for get_component_by_id

        Get a single component
        """
        pass

    def test_get_components(self):
        """
        Test case for get_components

        List components
        """
        pass


if __name__ == '__main__':
    unittest.main()
