# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.7.0-04
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.page_component_xo import PageComponentXO


class TestPageComponentXO(unittest.TestCase):
    """ PageComponentXO unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPageComponentXO(self):
        """
        Test PageComponentXO
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.page_component_xo.PageComponentXO()
        pass


if __name__ == '__main__':
    unittest.main()
