# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.7.0-04
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import nexuscli
from nexuscli.rest import ApiException
from nexuscli.models.page_task_xo import PageTaskXO


class TestPageTaskXO(unittest.TestCase):
    """ PageTaskXO unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPageTaskXO(self):
        """
        Test PageTaskXO
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = nexuscli.models.page_task_xo.PageTaskXO()
        pass


if __name__ == '__main__':
    unittest.main()
