# coding: utf-8

"""
    Nexus Repository Manager REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.7.0-04
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ScriptXO(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'content': 'str',
        'type': 'str'
    }

    attribute_map = {
        'name': 'name',
        'content': 'content',
        'type': 'type'
    }

    def __init__(self, name=None, content=None, type=None):
        """
        ScriptXO - a model defined in Swagger
        """

        self._name = None
        self._content = None
        self._type = None

        if name is not None:
          self.name = name
        if content is not None:
          self.content = content
        if type is not None:
          self.type = type

    @property
    def name(self):
        """
        Gets the name of this ScriptXO.

        :return: The name of this ScriptXO.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this ScriptXO.

        :param name: The name of this ScriptXO.
        :type: str
        """
        if name is not None and not re.search('^[a-zA-Z0-9\\-]{1}[a-zA-Z0-9_\\-\\.]*$', name):
            raise ValueError("Invalid value for `name`, must be a follow pattern or equal to `/^[a-zA-Z0-9\\-]{1}[a-zA-Z0-9_\\-\\.]*$/`")

        self._name = name

    @property
    def content(self):
        """
        Gets the content of this ScriptXO.

        :return: The content of this ScriptXO.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """
        Sets the content of this ScriptXO.

        :param content: The content of this ScriptXO.
        :type: str
        """

        self._content = content

    @property
    def type(self):
        """
        Gets the type of this ScriptXO.

        :return: The type of this ScriptXO.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this ScriptXO.

        :param type: The type of this ScriptXO.
        :type: str
        """

        self._type = type

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ScriptXO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
